version: '3.3'

services:
  n_postgres:
    container_name: n_postgres
    hostname: n_postgres
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    command: postgres -c config_file=/etc/postgresql.conf
    ports:
      - "5435:5432"
    networks:
      - n_notifier
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      PGDATA: /data/postgres
    volumes:
      - ./configs/postgres/postgres.conf:/etc/postgresql.conf
      - ./data/postgres:/data/postgres

networks:
  n_notifier:
    driver: bridge