version: '3.3'

services:
  n_postgres:
    container_name: n_postgres
    hostname: n_postgres
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    command: postgres -c config_file=/etc/postgresql.conf
    ports:
      - "5435:5432"
    networks:
      - default
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      PGDATA: /data/postgres
    volumes:
      - ./configs/postgres/postgres.conf:/etc/postgresql.conf
      - ./data/postgres:/data/postgres

  n_parser:
    container_name: n_parser
    hostname: n_parser
    image: local/parser:1.0
    depends_on:
      - "n_postgres"
    build:
      context: ./docker_images/rate_loader/
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgresql://pguser:pgpassword@n_postgres:5432/notifier?serverVersion=11&charset=utf8"
      APP_ENV: "dev"
    networks:
      - default
    volumes:
      - ./data/n_parser:/var/www/vhosts/notifier
      - ./configs/n_parser/php.ini:/etc/php/8.1/cli/php.ini:delegated

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1